server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffeemachine
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.springdoc: INFO
    org.flywaydb: INFO